Passport auth
movableink/doorman pull request #54
Opened 2020-02-06 21:42 UTC by aackerman

The main goal here is to replace `everyauth`, because it is using a soon to be unsupported auth mechanism for github. It's also been several years since `everyauth` has had a commit. Passport is getting ongoing support and feels like a good option for replacement.

I've also gone ahead and replaced `jade` with `pug`, which was very easy. I did this because npm auditing said that a dependency of the version of jade we use had an RCE advisory open.

I put all of the authentication logic in the `ProxyDomain` class that I created to rewrite the `Domain` class, this was mainly for ease of testing having everything in one file. I don't have an issue with moving it, but I think the separation would really only matter if we intended to add more auth schemes.

I did manual testing with all three auth schemes, including checking required email, domain, and github org, and handling for public paths.

Looking forward to getting some feedback on the changes.

2020-02-06 21:45 UTC, mnutt commented on package.json
>      "jade": "1.6.0",
can probably get rid of jade now?

2020-02-06 21:46 UTC, aackerman commented on package.json
>      "jade": "1.6.0",
Yep, thanks.

2020-02-06 22:24 UTC, mnutt commented
This looks great and came together amazingly fast. It'll take me a little bit to work through the full set of changes.

2020-02-07 02:03 UTC, mnutt requested changes

2020-02-07 02:03 UTC, mnutt commented on lib/proxy_domain.js
> +        if (config.token && config.token == token) {
I think here we may want to prevent timing attacks with a function like:
```javascript
function safeCompare(a, b) {
  return crypto.timingSafeEqual(Buffer.from(a), Buffer.from(b));
}
```

2020-02-07 02:03 UTC, mnutt commented on lib/proxy_domain.js
> +  return valids.some(validOrg => orgs.some(org => validOrg == org));
I think we may not need `some` on the inner one:
```suggestion
  return orgs.some(org => valids.includes(org));
```

2020-02-07 02:03 UTC, mnutt commented on lib/proxy_domain.js
> +  return valids.some(validEmail => emails.some(email => email == validEmail));
I think this can be:
```suggestion
  return emails.some(email => validEmails.includes(email));
```

2020-02-07 02:03 UTC, mnutt commented on lib/proxy_domain.js
> +    return req.user != null;
It's a toss-up but I might consider just `return !!req.user;` since I'm a little worried that someone might come along later and notice the linter wanting to change `!=` to `!==`, at which point an `undefined` user would return authenticated.

2020-02-07 13:24 UTC, aackerman commented on lib/proxy_domain.js
> +    return req.user != null;
That's a decent concern, updated.

2020-02-07 13:25 UTC, aackerman commented on lib/proxy_domain.js
> +        if (config.token && config.token == token) {
You got it

2020-02-07 13:25 UTC, aackerman commented on lib/proxy_domain.js
> +  return valids.some(validEmail => emails.some(email => email == validEmail));
Done

2020-02-07 13:25 UTC, aackerman commented on lib/proxy_domain.js
> +  return valids.some(validOrg => orgs.some(org => validOrg == org));
And done

2020-02-07 13:45 UTC, mnutt approved these changes
Looks great!

2020-02-07 13:57 UTC, mchesler approved these changes
This looks great!  I'm amazed by how quickly it came together.  We can launch a second doorman instance and do some testing with it in production if you think it's worthwhile.

2020-02-09 18:29 UTC, mchesler commented
I just noticed that this is branched from `deploy-production`.  While `deploy-production` theoretically represents the right code to branch from, this should be a PR to merge into the `multi-domain` branch (which should probably be merged to `master` already)

2020-02-10 13:53 UTC, aackerman commented
@mchesler I've updated the base branch.

2020-02-10 15:41 UTC, aackerman commented
Ok, removed `everyauth`. I believe that's the last thing to do.

2020-02-10 20:12 UTC, merged